#include <iostream>

using namespace std;

int main()
{
    //system generated exception
    int a=90/0;
    
    // try{
    //     int num=0;
    //     cin>>num;
    //     if(num==45){
    //         throw(num);
    //     }
    //     else{
    //         num=num+10;
    //         cout<<num;
    //     }
    // }
    // catch(int e){
    //     cout<<"it is an exception";
    // }

    return 0;
}
